
import { CricketData } from './types';

export const CRICKET_TEMPLATES: CricketData[] = [
  {
    id: 'dumb',
    name: '呆物',
    grade: 0,
    hp: 20,
    sp: 20,
    vigor: 0,
    strength: 0,
    bite: 0,
    deadliness: 0,
    critDamage: 0,
    injuryOdds: 0,
    defence: 0,
    damageReduce: 0,
    counter: 0,
    skillIds: []
  },
  {
    id: 'needle',
    name: '绣花针',
    grade: 8,
    hp: 40,
    sp: 50,
    vigor: 1,
    strength: 1,
    bite: 1,
    deadliness: 85,
    critDamage: 45,
    injuryOdds: -10,
    defence: 0,
    damageReduce: 0,
    counter: 50,
    skillIds: ['poison_cone']
  },
  {
    id: 'spear',
    name: '两头枪',
    grade: 8,
    hp: 110,
    sp: 110,
    vigor: 7,
    strength: 13,
    bite: 7,
    deadliness: 20,
    critDamage: 8,
    injuryOdds: 15,
    defence: 0,
    damageReduce: 0,
    counter: 100,
    skillIds: ['iron_shell']
  },
  {
    id: 'bell',
    name: '吹铃',
    grade: 8,
    hp: 80,
    sp: 70,
    vigor: 22,
    strength: 5,
    bite: 6,
    deadliness: 40,
    critDamage: 5,
    injuryOdds: 0,
    defence: 0,
    damageReduce: 0,
    counter: 40,
    skillIds: ['soul_taking']
  },
  {
    id: 'yellow_horse',
    name: '跑马黄',
    grade: 8,
    hp: 140,
    sp: 150,
    vigor: 4,
    strength: 7,
    bite: 4,
    deadliness: 55,
    critDamage: 5,
    injuryOdds: -5,
    defence: 55,
    damageReduce: 10,
    counter: 120,
    skillIds: ['run_horse']
  },
  {
    id: 'jade_hoe',
    name: '玉锄头',
    grade: 8,
    hp: 120,
    sp: 120,
    vigor: 9,
    strength: 12,
    bite: 13,
    deadliness: 25,
    critDamage: 10,
    injuryOdds: 10,
    defence: 30,
    damageReduce: 8,
    counter: 45,
    skillIds: ['raise_sword']
  },
  {
    id: 'armor',
    name: '披袍轩甲',
    grade: 8,
    hp: 280,
    sp: 200,
    vigor: 6,
    strength: 6,
    bite: 6,
    deadliness: 0,
    critDamage: 0,
    injuryOdds: 20,
    defence: 80,
    damageReduce: 5,
    counter: 70,
    skillIds: ['black_armor']
  },
  {
    id: 'fan_sheng',
    name: '反生名',
    grade: 8,
    hp: 90,
    sp: 90,
    vigor: 7,
    strength: 11,
    bite: 9,
    deadliness: 65,
    critDamage: 12,
    injuryOdds: -15,
    defence: 0,
    damageReduce: 0,
    counter: 95,
    skillIds: ['brave']
  },
  {
    id: 'cinnabar',
    name: '朱砂额',
    grade: 8,
    hp: 140,
    sp: 100,
    vigor: 8,
    strength: 9,
    bite: 13,
    deadliness: 30,
    critDamage: 18,
    injuryOdds: 0,
    defence: 30,
    damageReduce: 8,
    counter: 40,
    skillIds: ['cinnabar_evil']
  },
  {
    id: 'monk',
    name: '头陀',
    grade: 8,
    hp: 180,
    sp: 160,
    vigor: 6,
    strength: 16,
    bite: 10,
    deadliness: 20,
    critDamage: 10,
    injuryOdds: 10,
    defence: 45,
    damageReduce: 18,
    counter: 45,
    skillIds: ['immovable']
  },
  {
    id: 'iron_bullet',
    name: '铁弹子',
    grade: 8,
    hp: 170,
    sp: 170,
    vigor: 5,
    strength: 24,
    bite: 8,
    deadliness: 0,
    critDamage: 0,
    injuryOdds: 30,
    defence: 35,
    damageReduce: 10,
    counter: 65,
    skillIds: ['spear_death']
  },
  {
    id: 'red_beard',
    name: '赤须',
    grade: 8,
    hp: 190,
    sp: 130,
    vigor: 8,
    strength: 10,
    bite: 10,
    deadliness: 35,
    critDamage: 18,
    injuryOdds: 5,
    defence: 30,
    damageReduce: 8,
    counter: 50,
    skillIds: ['sacrifice']
  },
  {
    id: 'jade_tail',
    name: '玉尾',
    grade: 8,
    hp: 90,
    sp: 90,
    vigor: 4,
    strength: 3,
    bite: 24,
    deadliness: 40,
    critDamage: 24,
    injuryOdds: 0,
    defence: 0,
    damageReduce: 0,
    counter: 40,
    skillIds: ['break_force']
  },
  {
    id: 'lamp',
    name: '油纸灯',
    grade: 8,
    hp: 180,
    sp: 120,
    vigor: 8,
    strength: 15,
    bite: 15,
    deadliness: 25,
    critDamage: 8,
    injuryOdds: 10,
    defence: 60,
    damageReduce: 8,
    counter: 75,
    skillIds: ['hundred_battles']
  },
  {
    id: 'tricolor',
    name: '真三色',
    grade: 8,
    hp: 220,
    sp: 180,
    vigor: 13,
    strength: 10,
    bite: 12,
    deadliness: 20,
    critDamage: 10,
    injuryOdds: 0,
    defence: 45,
    damageReduce: 10,
    counter: 40,
    skillIds: ['true_blood']
  },
  {
    id: 'grass',
    name: '草三段',
    grade: 8,
    hp: 150,
    sp: 200,
    vigor: 10,
    strength: 9,
    bite: 11,
    deadliness: 45,
    critDamage: 14,
    injuryOdds: 0,
    defence: 25,
    damageReduce: 15,
    counter: 55,
    skillIds: ['grass_talent']
  },
  {
    id: 'purple_yellow',
    name: '真紫黄',
    grade: 8,
    hp: 160,
    sp: 190,
    vigor: 11,
    strength: 12,
    bite: 10,
    deadliness: 25,
    critDamage: 20,
    injuryOdds: 20,
    defence: 20,
    damageReduce: 20,
    counter: 45,
    skillIds: ['change']
  },
  {
    id: 'plum_wing',
    name: '梅花翅',
    grade: 8,
    hp: 90,
    sp: 140,
    vigor: 24,
    strength: 1,
    bite: 14,
    deadliness: 70,
    critDamage: 10,
    injuryOdds: -20,
    defence: 0,
    damageReduce: 0,
    counter: 80,
    skillIds: ['spirit_channel']
  },
  {
    id: 'sky_blue',
    name: '天蓝青',
    grade: 8,
    hp: 290,
    sp: 290,
    vigor: 12,
    strength: 11,
    bite: 13,
    deadliness: 35,
    critDamage: 15,
    injuryOdds: 0,
    defence: 35,
    damageReduce: 15,
    counter: 45,
    skillIds: ['tian_guang']
  },
  {
    id: 'brocade',
    name: '三段锦',
    grade: 8,
    hp: 150,
    sp: 150,
    vigor: 20,
    strength: 20,
    bite: 20,
    deadliness: 50,
    critDamage: 20,
    injuryOdds: 0,
    defence: 30,
    damageReduce: 10,
    counter: 50,
    skillIds: ['brocade_intimidate']
  },
  {
    id: 'three_prince',
    name: '三太子',
    grade: 8,
    hp: 80,
    sp: 460,
    vigor: 8,
    strength: 7,
    bite: 9,
    deadliness: 75,
    critDamage: 1,
    injuryOdds: 15,
    defence: 75,
    damageReduce: 50,
    counter: 85,
    skillIds: ['red_lotus']
  },
  {
    id: 'eight_failures',
    name: '八败',
    grade: 8,
    hp: 180,
    sp: 800,
    vigor: 1,
    strength: 1,
    bite: 1,
    deadliness: 95,
    critDamage: 1,
    injuryOdds: -55,
    defence: 95,
    damageReduce: 25,
    counter: 800,
    skillIds: ['reverse_fate']
  },
  // Add more low grade ones without skills
  {
    id: 'zhen_qing',
    name: '真青',
    grade: 7,
    hp: 200,
    sp: 150,
    vigor: 10,
    strength: 11,
    bite: 12,
    deadliness: 15,
    critDamage: 5,
    injuryOdds: 15,
    defence: 35,
    damageReduce: 10,
    counter: 65,
    skillIds: []
  },
  {
    id: 'zhen_huang',
    name: '真黄',
    grade: 7,
    hp: 150,
    sp: 200,
    vigor: 9,
    strength: 13,
    bite: 10,
    deadliness: 25,
    critDamage: 8,
    injuryOdds: 10,
    defence: 30,
    damageReduce: 12,
    counter: 45,
    skillIds: []
  },
  {
    id: 'zhen_zi',
    name: '真紫',
    grade: 7,
    hp: 140,
    sp: 140,
    vigor: 11,
    strength: 8,
    bite: 11,
    deadliness: 35,
    critDamage: 10,
    injuryOdds: 5,
    defence: 25,
    damageReduce: 15,
    counter: 50,
    skillIds: []
  },
  {
    id: 'zhen_hong',
    name: '真红',
    grade: 7,
    hp: 100,
    sp: 100,
    vigor: 6,
    strength: 6,
    bite: 15,
    deadliness: 50,
    critDamage: 14,
    injuryOdds: -5,
    defence: 0,
    damageReduce: 0,
    counter: 55,
    skillIds: []
  },
  {
    id: 'zhen_wu',
    name: '真乌',
    grade: 7,
    hp: 130,
    sp: 90,
    vigor: 7,
    strength: 15,
    bite: 9,
    deadliness: 20,
    critDamage: 5,
    injuryOdds: 5,
    defence: 50,
    damageReduce: 8,
    counter: 80,
    skillIds: []
  },
  {
    id: 'zhen_bai',
    name: '真白',
    grade: 7,
    hp: 90,
    sp: 130,
    vigor: 15,
    strength: 4,
    bite: 8,
    deadliness: 45,
    critDamage: 12,
    injuryOdds: -10,
    defence: 0,
    damageReduce: 0,
    counter: 60,
    skillIds: []
  }
];
